apiVersion: v1
kind: Pod
metadata: 
  name: centos
  namespace: default
spec:
  containers:
  - image: centos
    command:
    - /bin/sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: centos
  restartPolicy: Always
