apiVersion: v1
kind: Pod
metadata: 
  name: dig
  namespace: default
spec:
  containers:
  - image: docker.io/azukiapp/dig
    command:
    - /bin/sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: dig
  restartPolicy: Always
