apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
data:
  bootJavaOpts: --eureka.client.service-url.defaultZone=http://eurekaserver/eureka/
  jvmOpts: -Xms256m -Xmx256m
  maintainer: chinoukin
