apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: service-hi
  name: service-hi
  namespace: default
spec:
  selector:
    matchLabels:
      run: service-hi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: service-hi
    spec:
      containers:
        - image: 192.168.70.133:5000/service-hi:latest
          imagePullPolicy: IfNotPresent
          name: service-hi
      restartPolicy: Always