apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: service-feign
  name: service-feign
  namespace: default
spec:
  selector:
    matchLabels:
      run: service-feign
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: service-feign
    spec:
      containers:
      - image: 192.168.70.133:5000/service-feign:latest
        imagePullPolicy: IfNotPresent
        name: service-feign
        #command: [ "java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/local/wiseapp/app.jar", "--eureka.client.service-url.defaultZone=http://eurekaserver/eureka/ -Xms256m -Xmx256m" ]
        #command: ["./entrypoint.sh"]
        #command: [ "/bin/sh", "-c", "bootJavaOpts=$(cat /etc/config/bootJavaOpts) jvmOpts=$(cat /etc/config/jvmOpts) && java -Djava.security.egd=file:/dev/./urandom -jar /app.jar $bootJavaOpts $jvmOpts" ]
        command:
          - "/bin/sh"
          - "-c"
          # - "bootJavaOpts=$(cat /etc/config/bootJavaOpts) && jvmOpts=$(cat /etc/config/jvmOpts) && java -Djava.security.egd=file:/dev/./urandom -jar /app.jar $bootJavaOpts $jvmOpts"
          - "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar $(cat /etc/config/bootJavaOpts) $(cat /etc/config/jvmOpts)"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: my-config
          items:
          - key: bootJavaOpts
            path: bootJavaOpts
          - key: jvmOpts
            path: jvmOpts
      imagePullSecrets:
      - name: mydocker-registry
      restartPolicy: Always