apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: service-feign
  name: service-feign
  namespace: default
spec:
  selector:
    matchLabels:
      run: service-feign
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: service-feign
    spec:
      containers:
      - image: 192.168.70.133:5000/service-feign:latest
        imagePullPolicy: IfNotPresent
        name: service-feign
        env:
        - name: bootJavaOpts
          valueFrom:
            configMapKeyRef:
              key: bootJavaOpts
              name: my-config
      imagePullSecrets:
      - name: mydocker-registry
      restartPolicy: Always