apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: service-feign
  name: service-feign
  namespace: default
spec:
  selector:
    matchLabels:
      run: service-feign
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: service-feign
    spec:
      containers:
      - image: 192.168.70.133:5000/service-feign:latest
        imagePullPolicy: IfNotPresent
        name: service-feign
        #command: [ "java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/local/wiseapp/app.jar", "--eureka.client.service-url.defaultZone=http://eurekaserver/eureka/" ]
        #command: [ "java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/local/wiseapp/app.jar", "$(/usr/bin/cat /etc/config/bootJavaOpts)" ]
        command: ["./entrypoint.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: my-config
          items:
          - key: bootJavaOpts
            path: bootJavaOpts
          - key: jvmOpts
            path: jvmOpts
      imagePullSecrets:
      - name: mydocker-registry
      restartPolicy: Always